# Generated by Django 4.2.4 on 2023-09-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('beer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('abv', models.FloatField(blank=True, null=True)),
                ('appearance', models.FloatField(blank=True, null=True)),
                ('aroma', models.FloatField(blank=True, null=True)),
                ('class_name', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('flavor', models.FloatField(blank=True, null=True)),
                ('large_category', models.CharField(blank=True, max_length=255, null=True)),
                ('mouthfeel', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_kor', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'beer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BeerSimilarity',
            fields=[
                ('beer_similarity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('beer1', models.BigIntegerField(blank=True, null=True)),
                ('beer2', models.BigIntegerField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'beer_similarity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('choice', models.BooleanField()),
            ],
            options={
                'db_table': 'preference',
                'managed': False,
            },
        ),
    ]
